{
  "dist": "trusty",
  "sudo": "require",
  "language" : "haskell"
  "compiler": "ghc",
  "before_install": [
    
  ],
  "install": [
    ""
  ]
  "script": [
    "ghc --version",
    "./make.sh"
  ],
  "group": "stable",
  "os": "linux"
}
